 language: elixir

 elixir: 
  - 1.6.4

addons:
  postgresql: '10.3'
  
services: 
  - postgresql

before_script:
  - cp config/travis.exs config/test.exs
  - mix do ecto.create, ecto.migrate

script: 
  - mix test

