language: elixir

elixir:
  - '1.6.4'

install:
  - mix local.rebar --force
  - mix local.hex --force
  - mix deps.get

addons:
  postgresql: '10.3'

services:
  - postgresql

before_script:
  - cp config/travis.exs config/test.exs
  - psql -c 'create database travis_ci_test;' -U postgres
  - mix do ecto.create, ecto.migrate

script:
  - mix test

